// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlE2wKPWZ99DD2KGqcVeXYMPe_cozE8Ts',
    appId: '1:652972449352:web:58c1471a80f7b367abc27d',
    messagingSenderId: '652972449352',
    projectId: 'tap-tennis',
    authDomain: 'tap-tennis.firebaseapp.com',
    databaseURL: 'https://tap-tennis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tap-tennis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvTaI4pEe9TOZHq_k_YCrD-q_ws_9psQ',
    appId: '1:652972449352:android:25ce205144f170ababc27d',
    messagingSenderId: '652972449352',
    projectId: 'tap-tennis',
    databaseURL: 'https://tap-tennis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tap-tennis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzK-cSKNVGQPmOCVUZhPXFRqiJcnDGElM',
    appId: '1:652972449352:ios:500c02bfb8affb50abc27d',
    messagingSenderId: '652972449352',
    projectId: 'tap-tennis',
    databaseURL: 'https://tap-tennis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tap-tennis.appspot.com',
    iosClientId: '652972449352-crp13tgsatdhth52vp8nd56bn6hign4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapTennis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzK-cSKNVGQPmOCVUZhPXFRqiJcnDGElM',
    appId: '1:652972449352:ios:500c02bfb8affb50abc27d',
    messagingSenderId: '652972449352',
    projectId: 'tap-tennis',
    databaseURL: 'https://tap-tennis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tap-tennis.appspot.com',
    iosClientId: '652972449352-crp13tgsatdhth52vp8nd56bn6hign4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapTennis',
  );
}
